"""Shared group2 metric thresholds and novice-report semantics."""

from __future__ import annotations

# Offline point-hit uses center-distance tolerance rather than business-eval X/Y axis tolerance.
GROUP2_OFFLINE_POINT_HIT_TOLERANCE_PX = 12.0

# Summary / failure-pattern thresholds used to flag dataset or localization risk.
GROUP2_SUMMARY_POINT_HIT_ALERT_THRESHOLD = 0.90
GROUP2_SUMMARY_LOW_IOU_ALERT_THRESHOLD = 0.80
GROUP2_DATASET_GAP_POINT_HIT_THRESHOLD = 0.80
GROUP2_LOCALIZATION_ALERT_CENTER_ERROR_PX = GROUP2_OFFLINE_POINT_HIT_TOLERANCE_PX

# Novice-facing model-test guidance thresholds.
GROUP2_MODELTEST_STRONG_POINT_HIT_THRESHOLD = 0.92
GROUP2_MODELTEST_STRONG_IOU_THRESHOLD = 0.85
GROUP2_MODELTEST_EFFECTIVE_POINT_HIT_THRESHOLD = GROUP2_DATASET_GAP_POINT_HIT_THRESHOLD
GROUP2_MODELTEST_EFFECTIVE_IOU_THRESHOLD = 0.70
GROUP2_MODELTEST_BOOTSTRAP_POINT_HIT_THRESHOLD = 0.65
GROUP2_MODELTEST_DATASET_GAP_IOU_THRESHOLD = 0.75
