classes:
  - id: 0
    name: icon_house
    zh_name: 房子
  - id: 1
    name: icon_leaf
    zh_name: 叶子
  - id: 2
    name: icon_ship
    zh_name: 船
  - id: 3
    name: icon_plane
    zh_name: 飞机
  - id: 4
    name: icon_car
    zh_name: 汽车
  - id: 5
    name: icon_bicycle
    zh_name: 自行车
  - id: 6
    name: icon_key
    zh_name: 钥匙
  - id: 7
    name: icon_lock
    zh_name: 锁
  - id: 8
    name: icon_camera
    zh_name: 相机
  - id: 9
    name: icon_star
    zh_name: 星星
  - id: 10
    name: icon_heart
    zh_name: 爱心
  - id: 11
    name: icon_paw
    zh_name: 爪印
  - id: 12
    name: icon_tree
    zh_name: 树
  - id: 13
    name: icon_flower
    zh_name: 花
  - id: 14
    name: icon_gift
    zh_name: 礼物
  - id: 15
    name: icon_music
    zh_name: 音符
  - id: 16
    name: icon_bell
    zh_name: 铃铛
  - id: 17
    name: icon_umbrella
    zh_name: 雨伞
  - id: 18
    name: icon_flag
    zh_name: 旗子
  - id: 19
    name: icon_globe
    zh_name: 地球
