shapes:
  - id: 0
    name: shape_001
    zh_name: 缺口形状001
  - id: 1
    name: shape_002
    zh_name: 缺口形状002
  - id: 2
    name: shape_003
    zh_name: 缺口形状003
  - id: 3
    name: shape_004
    zh_name: 缺口形状004
  - id: 4
    name: shape_005
    zh_name: 缺口形状005
  - id: 5
    name: shape_006
    zh_name: 缺口形状006
  - id: 6
    name: shape_007
    zh_name: 缺口形状007
  - id: 7
    name: shape_008
    zh_name: 缺口形状008
  - id: 8
    name: shape_009
    zh_name: 缺口形状009
  - id: 9
    name: shape_010
    zh_name: 缺口形状010
  - id: 10
    name: shape_011
    zh_name: 缺口形状011
  - id: 11
    name: shape_012
    zh_name: 缺口形状012
  - id: 12
    name: shape_013
    zh_name: 缺口形状013
  - id: 13
    name: shape_014
    zh_name: 缺口形状014
  - id: 14
    name: shape_015
    zh_name: 缺口形状015
  - id: 15
    name: shape_016
    zh_name: 缺口形状016
  - id: 16
    name: shape_017
    zh_name: 缺口形状017
  - id: 17
    name: shape_018
    zh_name: 缺口形状018
  - id: 18
    name: shape_019
    zh_name: 缺口形状019
  - id: 19
    name: shape_020
    zh_name: 缺口形状020
  - id: 20
    name: shape_021
    zh_name: 缺口形状021
  - id: 21
    name: shape_022
    zh_name: 缺口形状022
  - id: 22
    name: shape_023
    zh_name: 缺口形状023
  - id: 23
    name: shape_024
    zh_name: 缺口形状024
  - id: 24
    name: shape_025
    zh_name: 缺口形状025
  - id: 25
    name: shape_026
    zh_name: 缺口形状026
  - id: 26
    name: shape_027
    zh_name: 缺口形状027
  - id: 27
    name: shape_028
    zh_name: 缺口形状028
  - id: 28
    name: shape_029
    zh_name: 缺口形状029
  - id: 29
    name: shape_030
    zh_name: 缺口形状030
  - id: 30
    name: shape_031
    zh_name: 缺口形状031
  - id: 31
    name: shape_032
    zh_name: 缺口形状032
  - id: 32
    name: shape_033
    zh_name: 缺口形状033
  - id: 33
    name: shape_034
    zh_name: 缺口形状034
  - id: 34
    name: shape_035
    zh_name: 缺口形状035
  - id: 35
    name: shape_036
    zh_name: 缺口形状036
  - id: 36
    name: shape_037
    zh_name: 缺口形状037
  - id: 37
    name: shape_038
    zh_name: 缺口形状038
  - id: 38
    name: shape_039
    zh_name: 缺口形状039
